// =============================================================================
//
// This file is generated by Magic Code Generator
//
// =============================================================================

// call the packages we need
let express = require('express');                   // call express
let app = express();                                // define our app using express
let bodyParser = require('body-parser');
let mongoose = require('mongoose');                 // Use Mongoose ODM to connect to MongoDB
// imported classes
{{#each collections}}
let {{name}} = new (require("./classes").{{tsClassPropertyName name}});
{{/each}}

// Constant section
const port = process.env.PORT || {{server.port}};   // set our port
const API_Path ="/";                                // base API service path

// configure app to use bodyParser()
// this will let us get the data from a POST
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json()); 

// ROUTES FOR OUR API
// =============================================================================
let router = express.Router();              // get an instance of the express Router

// middleware to use for all requests
router.use(function (req, res, next) {
    next(); // make sure we go to the next routes and don't stop here
});

{{#each collections}}
{{#if methods}}

//----------------------------------------------------
// Route for {{path}}
// ----------------------------------------------------
router.route('{{path}}/model')
    .get(function (req, res) {
        {{name}}.query(req, res);
    });
router.route('{{path}}/querytemplate')
    .get(function(req, res) {
        {{name}}.template(req, res);
    })
router.route('{{path}}')
    .get(function (req, res) {
      {{#if methods.get}}
        {{name}}.get(req, res);
      {{else}}
        res.sendCode(405);
      {{/if}}
    })
    .post(function (req, res) {
      {{#if methods.post}}
        {{name}}.post(req, res);
      {{else}}
        res.sendCode(405);
      {{/if}}
    })
    .put(function(req, res) {
      {{#if methods.put}}
         {{name}}.post(req, res);
      {{else}}
        res.sendCode(405);
      {{/if}}
    })
    .delete(function(req, res) {
      {{#if methods.delete}}
        {{name}}.remove(req, res);
      {{else}}
        res.sendCode(405);
      {{/if}}
    })

{{/if}}
{{/each}}

// REGISTER OUR ROUTES -------------------------------
// all of our routes will be prefixed with /api
app.use(API_Path, router);

// START THE SERVER
// =============================================================================
app.listen(port);
console.log('Micro service started on port ' + port);